services:
  transport-postgres:
    restart: unless-stopped

  audit-postgres:
    restart: unless-stopped

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:19092,PLAINTEXT_HOST://${DEV_PUBLIC_HOST:?DEV_PUBLIC_HOST is required}:9092"
    restart: unless-stopped

  kafka-connect:
    restart: unless-stopped

  kafka-ui:
    restart: unless-stopped

  transport-service:
    image: ${TRANSPORT_IMAGE}
    restart: unless-stopped

  audit-consumer:
    image: ${AUDIT_IMAGE}
    restart: unless-stopped

  prometheus:
    restart: unless-stopped

  grafana:
    restart: unless-stopped

  postgres-exporter:
    restart: unless-stopped