spring:
  application:
    name: audit-consumer

  datasource:
    url: jdbc:postgresql://${AUDIT_DB_HOST:localhost}:${AUDIT_DB_PORT:5433}/${AUDIT_DB_NAME:audit}
    username: ${AUDIT_DB_USERNAME:audit}
    password: ${AUDIT_DB_PASSWORD:audit}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  flyway:
    enabled: true
#    url: jdbc:postgresql://${AUDIT_DB_HOST:localhost}:${AUDIT_DB_PORT:5433}/${AUDIT_DB_NAME:audit}
#    user: ${AUDIT_DB_USERNAME:audit}
#    password: ${AUDIT_DB_PASSWORD:audit}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: audit-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: ${AUDIT_KAFKA_MAX_POLL_RECORDS:100}
    listener:
      concurrency: ${AUDIT_KAFKA_CONCURRENCY:3}
      ack-mode: record

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        audit.cdc.end.to.end: true
    tags:
      application: ${spring.application.name}

audit:
  kafka:
    topics:
      transport: transport.public.transport
      job: transport.public.job
      container: transport.public.container

    retry:
      interval-ms: ${AUDIT_RETRY_INTERVAL_MS:2000}
      max-retries: ${AUDIT_RETRY_MAX_RETRIES:2}

    dlt:
      partitions: ${AUDIT_DLT_PARTITIONS:3}
      replication-factor: ${AUDIT_DLT_REPLICATION_FACTOR:1}

    dlt-replay:
      enabled: ${AUDIT_DLT_REPLAY_ENABLED:false}
      group-id: ${AUDIT_DLT_REPLAY_GROUP_ID:audit-dlt-replay}