GRANT USAGE ON SCHEMA public TO debezium;

GRANT SELECT ON TABLE transport TO debezium;
GRANT SELECT ON TABLE job TO debezium;
GRANT SELECT ON TABLE container TO debezium;

ALTER TABLE transport REPLICA IDENTITY FULL;
ALTER TABLE job REPLICA IDENTITY FULL;
ALTER TABLE container REPLICA IDENTITY FULL;